### ISSUE TITLE
Port to cryptography and drop M2Crypto dependency

### ISSUE THREAD

**Issue by kumar303** [brightinteractive/django-encrypted-cookie-session#16]
M2Crypto is a beast to install and requires unofficial patches on many Linux distros now. I think we can port encrypted cookies to use [cryptography](https://cryptography.io/en/latest/) instead but I haven't looked at it in detail.

**Comment by kumar303** [comment]
@frankoid if you can add me as a collaborator to this repo I can assign this to myself. I should have time for a patch soon-ish.

**Comment by frankoid** [comment]
This sounds useful, I recently had to install M2Crypto [from git](https://github.com/martinpaljak/M2Crypto/commit/9abed178ed257d1bd2efbb16f7512e964f85d006) to get it to install on a RHEL 7 machine. Dropping support for M2Crypto might be disruptive though (e.g. if some people have problems installing cryptography) but I'm not dead set against it.

@kumar303 I've added you with read permissions initially but not sure whether that lets you assign issues.

**Comment by kumar303** [comment]
Thanks. It looks like I don't have permissions to assign it to myself but if you want to assign it to me then that will help me track it on my all-of-github dashboard.

**Comment by kumar303** [comment]
but either way, no biggie, I should have time for a patch soon

**Comment by frankoid** [comment]
It won't let me assign it to you either :(. I can assign it, but it looks like I can only assign it to people with write permission on the repo.

**Comment by kumar303** [comment]
I have a patch that's ready for this. Can you take a look? https://github.com/brightinteractive/django-encrypted-cookie-session/pull/18 I tested it on a Django 1.7 app and it seems to be working fine.
